#!/usr/bin/env python3
"""Catch the documentation drift this project keeps producing.

Not a substitute for reading the numbers -- it cannot know whether a sentence
matches a table.  It catches the mechanical half: results that no script
produces, scripts whose results were never regenerated, references to
experiments that do not exist, and counts in the README that have gone stale.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    problems: list[str] = []
    scripts = sorted(ROOT.glob("experiments/exp*.py"))
    results = sorted(ROOT.glob("experiments/results/*.md"))
    names = {p.stem for p in scripts}

    for script in scripts:
        out = ROOT / "experiments" / "results" / f"{script.stem}.md"
        if not out.exists():
            problems.append(f"{script.name} has never written {out.name}")

    for out in results:
        text = out.read_text()
        stamp = re.search(r"_Generated by `experiments/([\w.]+)`", text)
        if not stamp:
            problems.append(f"{out.name} has no generation stamp")
        elif stamp.group(1) != f"{out.stem}.py":
            problems.append(f"{out.name} was written by {stamp.group(1)}")
        if out.stem not in names and out.stem != "index":
            problems.append(f"{out.name} has no script")

    docs = [ROOT / "README.md"] + sorted(ROOT.glob("docs/*.md"))
    for doc in docs:
        text = doc.read_text()
        for ref in sorted(set(re.findall(r"\bexp\d{2}\b", text))):
            if not any(name.startswith(ref) for name in names):
                problems.append(f"{doc.name} cites {ref}, which does not exist")

    readme = (ROOT / "README.md").read_text()
    tens = {"twenty": 20, "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60,
            "seventy": 70, "eighty": 80, "ninety": 90}
    units = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
             "seven": 7, "eight": 8, "nine": 9}
    words = dict(tens)
    for tname, tval in tens.items():
        for uname, uval in units.items():
            words[f"{tname}-{uname}"] = tval + uval
    claimed = re.search(r"experiments/\s+([a-z-]+) reproducible scripts", readme)
    if claimed:
        want = words.get(claimed.group(1))
        if want is None:
            problems.append(f"README script count '{claimed.group(1)}' unrecognised")
        elif want != len(scripts):
            problems.append(f"README says {claimed.group(1)} scripts; there are "
                            f"{len(scripts)}")
    else:
        problems.append("README no longer states a script count")

    stated = re.search(r"tests/\s+(\d+) tests", readme)
    if stated:
        counted = sum(len(re.findall(r"^def test_", p.read_text(), re.M))
                      for p in ROOT.glob("tests/test_*.py"))
        if int(stated.group(1)) != counted:
            problems.append(f"README says {stated.group(1)} tests; the files define "
                            f"{counted}")

    for line in problems:
        print(f"drift: {line}")
    print(f"\n{len(scripts)} scripts, {len(results)} results, {len(problems)} problems")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
